### ISSUE TITLE
Unable to to fetch submodules

### ISSUE THREAD

**Issue by timofonic** [Argon-/mpv-config#12]
IMPORTANT: This isn't a replication of [Some files are just links, not real files](https://github.com/Argon-/mpv-config/issues/9).

### 1: Extreme?

```
root@laptop /etc# git clone --verbose --recursive  -j12 https://github.com/Argon-/mpv-config/
Cloning into bare repository 'mpv-config.git'...
POST git-upload-pack (165 bytes)
remote: Counting objects: 510, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 510 (delta 0), reused 1 (delta 0), pack-reused 507
Receiving objects: 100% (510/510), 276.01 KiB | 134.00 KiB/s, done.
Resolving deltas: 100% (295/295), done.

```

#### Result:

_**NOTE: The bold letters means those files are wrong in some reason.**_ 
1. Empty directory. 
2. Dead symlink

root@laptop /e/mpv-config# tree
.
├── encoding-profiles.conf
├── input.conf
├── lua-settings
│   ├── osc.conf
│   ├── stats.conf
│   └── torque-progressbar.conf
├── mpv.conf
├── scripts
│   ├── autodeint.lua
│   ├── auto-profiles-functions.lua
│   ├── **auto-profiles.lua -> mpv-scripts/auto-profiles.lua**
│   ├── auto-save-state.lua
│   ├── autosub.lua
│   ├── deactivated
│   │   ├── auto-options-old.lua
│   │   └── ontop-playback.lua
│   ├── **fix-sub-timing.lua -> mpv-scripts/fix-sub-timing.lua**
│   ├── **mines.lua -> mpv-scripts/mines.lua**
│   ├── **mpv-repl**
│   ├── **mpv-scripts**
│   ├── progressbar.lua
│   ├── **repl.lua -> mpv-repl/repl.lua**
│   └── stats.lua -> /Users/Julian/Documents/Code/Lua/mpv-stats/stats.lua
├── shaders
│   ├── **AdaptiveSharpen**
│   ├── **adaptive-sharpen.glsl -> AdaptiveSharpen/adaptive-sharpen.glsl**
│   ├── **FineSharp**
│   ├── **FineSharp.glsl -> FineSharp/FineSharp.glsl**
│   ├── **KrigBilateral**
│   ├── **mpv-prescalers**
│   ├── **nnedi3-nns32-win8x4.hook -> mpv-prescalers/nnedi3-nns32-win8x4.hook**
│   ├── **nnedi3-nns32-win8x4-yuv.hook -> mpv-prescalers/nnedi3-nns32-win8x4-yuv.hook**
│   ├── **nnedi3-nns64-win8x4.hook -> mpv-prescalers/nnedi3-nns64-win8x4.hook**
│   ├── **nnedi3-nns64-win8x4-yuv.hook -> mpv-prescalers/nnedi3-nns64-win8x4-yuv.hook**
│   ├── **SSimDownscaler**
│   ├── **SSimDownscaler.glsl -> SSimDownscaler/SSimDownscaler.glsl**
│   ├── **SSimSuperRes**
│   ├── **SSimSuperRes.glsl -> SSimSuperRes/SSimSuperRes.glsl**
│   └── update.sh
└── vs-scripts
    ├── conv-tests.py
    ├── decimate.py
    ├── f3kdb.py
    ├── mi-offline.py
    ├── motion-interpolation-brokenfps.py
    └── motion-interpolation.py

13 directories, 33 files

Then I tried in all possible ways this commands in all probabilities and changed it to all different variations. Total OCD, I know.

> root@laptop /e/m/scripts# git submodule update --init --recursive

There's no way to make them copied.

I also noticed other projects use submodules and they are clickable on GitHub.com site, despite being from third party repos.

Heres a similar issue...
https://stackoverflow.com/questions/11019059/unable-to-clone-submodules-with-recursive

WHY? Please explain it to me. I have no idea :(

**Comment by Ikke** [comment]
There is no `.gitmodules` file present, so these are not proper git submodules. That's why git is not able to populate those directories, because it has no idea where to find the repositories.

**Comment by timofonic** [comment]
@Ikke Thanks a lot. Are they easy to recreate? It seems these submodules go to the following repos

scripts
* https://github.com/wm4/mpv-scripts
* https://github.com/rossy/mpv-repl

shaders
* [/bacondither/Adaptive-sharpen](https://github.com/bacondither/Adaptive-sharpen)
* [/bjin/mpv-prescalers](https://github.com/bjin/mpv-prescalers)
* [/igv/SSimSuperRes.glsl](https://gist.github.com/igv/2364ffa6e81540f29cb7ab4c9bc05b6b)
* [/igv/SSimDownscaler.glsl](https://gist.github.com/igv/36508af3ffc84410fe39761d6969be10)
* [/igv/FineSharp.glsl](https://gist.github.com/igv/a9a21ad1f6dd7d0b4452)
* [/igv/KrigBilateral](https://gist.github.com/igv/a015fc885d5c22e6891820ad89555637#file-krigbilateral-glsl)

Thanks in advance!

**Comment by Argon-** [comment]
Yes, as mentioned these are not submodules but just git repos within a git repo. 
I should probably change that...

**Comment by timofonic** [comment]
@Argon- Do you have issues changing it? Are you willing to change it? Thanks for your reply!
