### ISSUE TITLE
betterchapters.lua -- wrong keybind names

### ISSUE THREAD

**Issue by Keith94** [Argon-/mpv-config#15]
In [betterchapters.lua](https://github.com/Argon-/mpv-config/blob/master/scripts/betterchapters.lua), it says the keybind names are `chapter_next`, `chapter_prev`. These don't do anything. The correct ones seem to be `chapterplaylist-next`, `chapterplaylist-prev` when added to `input.conf`.

**Comment by Argon-** [comment]
Indeed. Will update it from its source when I get around to it.
However, are you not using the version from https://github.com/mpv-player/mpv/issues/4738#issuecomment-321298846 anyway?

**Comment by Keith94** [comment]
I was using that version previously, but I was seemingly limited to *two* key bindings unless I used a second copy of the .Lua file.

With your version... I can bind everything in input.conf just fine as long as I use the *correct* key bind names.

**Comment by Argon-** [comment]
No, this kind of calling a script from input.conf definitely works the same for both scripts. The question is just which keys to use.
I switched to the version linked above (https://github.com/Argon-/mpv-config/blob/master/scripts/betterchapters.lua#L20) but changed the name for keybindings so it is compatible with the previous version (chapterplaylist-next/chapterplaylist-prev)

**Comment by Keith94** [comment]
OK now it's looking great. Thanks a lot!!
