### ISSUE TITLE
Some questions about betterchapters

### ISSUE THREAD

**Issue by kesdoputr** [Argon-/mpv-config#16]
Hello, i'm using your betterchapters.lua but i have some questions.
By default, mpv treat the file start as chapter 0
ex.
If i have a file with chapter 1  at 5min, and now i'm at 2min, and i press PGDWN to go previous chapter 
●Without betterchapters→mpv will go to file start
●With betterchapters→mpv will go to previous file

Is it possible to have the same bahavior when i use betterchapters.lua?(treat the file start as chaper 0)

Thanks for your watching.

**Comment by Argon-** [comment]
Just for clarification: not my script. It was written bu someone else as indicated in the first line. 

Now as for your problem, to be honest I've never noticed this and will need to test it first. I feel like I've used it in the past to seek "back" to the start of a file but I might remember it wrong. 
Interestingly, looking at the script (I'm on my phone, no mpv available) it should actually work. Are you sure you are within the first chapter already?

**Comment by Argon-** [comment]
Just tested it and I can't reproduce your problem. Works for me.

**Comment by kesdoputr** [comment]
It's strange~~i test again and get the same result.
When the file's chapter 1 is not at 00:00:00 i can't use hotkey back to file start.
I'm using mpv x64 at windows 7 SP1 X64

PS.I test with no other config, just compare with betterchapters.

**Comment by Argon-** [comment]
How do you bind the script to a key? By editing the script file or with input.conf?

**Comment by kesdoputr** [comment]
I try both method
●edit the script directly
```
mp.add_key_binding("@", "chapterplaylist-next", function() chapter_seek(1) end)
mp.add_key_binding("!", "chapterplaylist-prev", function() chapter_seek(-1) end)
```
●use the setting in your input.conf
```
z      script-binding betterchapters/chapterplaylist-next #; show-text "${?chapter:Chapter: ${chapter}}"
Z      script-binding betterchapters/chapterplaylist-prev #; show-text "${?chapter:Chapter: ${chapter}}"
```

But i get the same result, i can only back to the first chapter, then show the playlist.

**Comment by kesdoputr** [comment]
It seems that, for example:
●Chapter 1 start at 00:00→will treat it to chapter0, so chapter+direction < 0→go to previous file
●Chapter 1 start at 05:00→will still treat it to chapter0, so chapter+direction < 0→go to previous file
(but i need it go to the file start)

**Comment by kesdoputr** [comment]
I try to add two line
```
local timepos = mp.get_property_number("time-pos")
if chapter+direction < 0 and timepos <= 5 then

```
And it seems ok now, when time over 5secs will first go to filestart(chaper 0)

**Comment by Argon-** [comment]
Now I get it.
An alternative would be to set the 0 to -1 but then you can't go back to the start of a file.
I assume this was the reason it was done like that. Without an "heuristic" (like your 5 seconds) you need to choose between "not being able to go to a previous file" and "not being able to seek to the start of your current file".
I suppose those 5 seconds will work fine but when chapters are shorter or start later, then there will be problems. Not sure if such files exist though.

**Comment by kesdoputr** [comment]
You are right, if there has a chapter shorter then 5sec, i can only back to this chapter and then goto previous file, but now seems work for most conditions.
Thanks for your reply, i wil close this issue first :)
