### ISSUE TITLE
Where do i place these?

### ISSUE THREAD

**Issue by wingedonezero** [Argon-/mpv-config#3]
Hello i would like to test your config ive never used a config before where do i place them? On ubuntu if that helps.

**Comment by Argon-** [comment]
I suppose you know these are mpv config files? You place them here: https://mpv.io/manual/stable/#files
A few of my scripts (the ones setting my VO) will not work for you though, not without potentially a lot of adjustments.
I think it's easier when you just look at various files and pick them on a case by case basis when you consider them worthwhile. This repo is not intended to be copied 1:1, this will most certainly not work.
