### ISSUE TITLE
fonts.conf

### ISSUE THREAD

**Issue by ghost** [Argon-/mpv-config#6]
1.What's the function of the file “fonts.conf”(font cache file?) and "encoding-profiles.conf"?   if I can delete these two files for redundant, during use ?
2.if it's useful ,What command (or how )to  generate  “fonts.conf”(font cache?)  for my own ?

**Comment by Argon-** [comment]
Fonts.conf is not useful anymore. I should remove it.
encoding-profiles.conf is my own (slightly modified) version of https://github.com/mpv-player/mpv/blob/master/etc/encoding-profiles.conf It's useful when you want to use mpv to encode stuff (https://mpv.io/manual/master/#encoding)

**Comment by ghost** [comment]
Thanks for your detailed reply
