### ISSUE TITLE
Location detection in OS X

### ISSUE THREAD

**Issue by AlbertDu** [Argon-/mpv-config#7]
I've observed there's location detection in auto_profiles_functions, but It didn't work in OS X, So I would like to know if there's a solution in Mac ?

**Comment by Argon-** [comment]
Oh it does work (I'm mostly on OSX myself) but you don't have the script I'm using (it's not in this repo). It's also probably not doing what it sounds like as it just checks if the current hostname equals a list of known hostnames.
I'm using such functions across my configurations and environments (bash, zsh, etc.) so I can use the same set of config files across all of my computers.

The file in question (slightly altered):

    DESKTOP_NAMES=("a" "b")
    MOBILE_NAMES=("c" "d" "e")

    function is-osx {
        [[ "$(uname)" == "Darwin" ]]
    }

    function is-linux {
        [[ "$(uname)" == "Linux" ]]
    }

    function is-desktop {
        loc=$(scutil --get ComputerName || hostname)
        for i in "${DESKTOP_NAMES[@]}"; do
            ([[ "$loc" == "$i" ]] || [[ "$loc" == "$i".local ]]) && return 0
        done
        return 1
    }

    function is-mobile {
        loc=$(scutil --get ComputerName || hostname)
        for i in "${MOBILE_NAMES[@]}"; do
            ([[ "$loc" == "$i" ]] || [[ "$loc" == "$i".local ]]) && return 0
        done
        return 1
    }
