### ISSUE TITLE
How to make the window on top automatically?

### ISSUE THREAD

**Issue by exxfzc** [Argon-/mpv-config#8]
hey ,I just have a small problem.when I open the mpv and  play video,I just want to make the mpv window ontop automatically,not for using "T" every time!!!
Is there any way to do it?Thank you!

**Comment by Argon-** [comment]
https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/ontop-playback.lua

**Comment by exxfzc** [comment]
The ontop-playback.lua doesn't solve my problem.It's just makes mpv ontop  when resuming playback,not ontop when open the video.

**Comment by Argon-** [comment]
Did you search the manual for "ontop"? https://mpv.io/manual/master/#options-ontop

**Comment by exxfzc** [comment]
I see and try to edit the mpv.conf,but failed.
<img width="643" alt="2017-06-17 19 06 51" src="https://user-images.githubusercontent.com/23161815/27252424-e259759a-5390-11e7-803b-72ae3f31da0e.png">

**Comment by Argon-** [comment]
Why failed? You are not using `ontop` in your config. You set the `ontop-level` but that's a different option.

**Comment by exxfzc** [comment]
I try to use ontop in my config,but still failed.I don't know why....
I have given up.
Whatever thank for everything.

**Comment by Argon-** [comment]
But you do realize you haven't even used it in your config above? It's not in there.
